### PR TITLE
Try to reproduce the problem described in the issue. (#14977)

### PR DESCRIPTION
**Pull request by chenrujun**

### CODE REVIEW

**Comment by chenrujun** [comment]
Hi, @fr4ncesco .
This is the sample for you.

**Comment by fr4ncesco** [comment]
Hello @chenrujun,

thanks for the example.

This reproduce exactly my problem.
The response coming from `/test` is somenthin like:
`PAQABAAAAAAAGV_bv21oQQ4ROqh0_1-tATUP190ThAMDdS88PAJlSVT7dcROcN2.... other chars`

Did you have the same behaviur? Is it correct?

I'm expecting somenthing like a JWT token `<header>.<body>.<signature>`

**Comment by chenrujun** [comment]
Hi, @fr4ncesco , 

> Did you have the same behaviur? Is it correct?

Yes, I have the same behavior, and it is correct.


please input your string to to https://jwt.ms/ , 
you string is encoded by BASE64, 
after decode by https://jwt.ms/ , 
you will see the `<header>.<body>.<signature>`

**Comment by fr4ncesco** [comment]
Hello @chenrujun 
sorry to may question but maybe my description is not clear. 
I know that the token is encoded base64 but the API don't give ma a valid JWT token.

Can be something related to the the App configuration from the portal?

I use a temporary user to provide you all the result:

Following a short video of my problem:
[https://youtu.be/JcFSjaD7tus](https://youtu.be/JcFSjaD7tus)

Spring API:

```Java
    @ResponseBody
    @RequestMapping("/test")
    public String test(OAuth2AuthenticationToken authentication) {

        final OAuth2AuthorizedClient authorizedClient =
            this.authorizedClientService.loadAuthorizedClient(
                authentication.getAuthorizedClientRegistrationId(),
                authentication.getName());

        return authorizedClient.getAccessToken().getTokenValue();
    }
```
Result on my browser form http://localhost:7180/test

Complete Response body:
```
PAQABAAAAAAAGV_bv21oQQ4ROqh0_1-tAnOrl5JSNa6DsnUx-DmxcJlIWKb0UUnebGwq4Jx7PWFBztBVBs4ldLyEXTYvd1FYC1hADDSL9TbdxJ-aO2XebDSmpIxaaWq7_DsnQkX_VQ1tklSdDY4t0qWSkL9zYrKqfFUYSAnc5J5o-mRxxV68-UmD9zokKg8hemUwhVdwgBgZPA5EprYloQAM2u_4LDCixptF7HbgpQR0dHQpnL3P5hc2mtYDGpk0aSiY1h8QotMAvAjv3zzCJQwIeJjB7DxUi4tbtO5VKmX-3xxt4PmsbcaxwNHngz7XoamILnpmjMxESvDOG5NaoEyhzM_zc1Nfy5Lq7TOfyOcplcjpDQzk7pDqsHeYnUEpbD5sUp1nCrqP_ohGJyJkrOsFzP0nPACWV60tTR9Y9p8aO1-aS3-OI0RPth1kbfrXZWKyngYFxyczmMX-vCjEF9ZMhTE0TeXUQjXgtO1tHw-GNcO_JCl8-fmqh_1XIOzHL4SGnE6yxDlJSZXyw2vJ3UpHb1G1CNO8vY8AbN28deqfKCq7snryrKT9BX-Cxp6XADpzGxhOzw7OcwJpl5Wz4AShqXR1JhoWaPqOpy_VgsRcZJCFi-jDBHyNGS6Mg1K2fYd1O3P6FfIsG0KOCSMxo2lb4PwXpCL88IAA
```

Instead with this API:
```Java
@ResponseBody
@RequestMapping("/test1")
public String test1(OAuth2AuthenticationToken authentication) {
        return ((DefaultOidcUser)authentication.getPrincipal()).getIdToken().getTokenValue();
}
````

I receive a correct token:

```
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImppYk5ia0ZTU2JteFBZck45Q0ZxUms0SzRndyIsImtpZCI6ImppYk5ia0ZTU2JteFBZck45Q0ZxUms0SzRndyJ9.eyJhdWQiOiI5YThjYzBkNy1iNTQ1LTQ2YzctYmY4ZS05MGY2ODIzNDlmMWQiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC85MzExYzcyNS0xMmEwLTRkNTYtODQ1Ny0wZWE4Nzg4M2IwYTIvIiwiaWF0IjoxNjAwMDc1MDgxLCJuYmYiOjE2MDAwNzUwODEsImV4cCI6MTYwMDA3ODk4MSwiYWlvIjoiRTJCZ1lEakgxNUVxKzZKdE92Ky83ZGxmM2RUbFl5LzU3UW5Uc3B6L25EZXp4QzFRcXg0QSIsImFtciI6WyJwd2QiXSwiZmFtaWx5X25hbWUiOiJEaXN0ZWZhbm8iLCJnaXZlbl9uYW1lIjoiRnJhbmNlc2NvIiwiaXBhZGRyIjoiODIuNTEuMzIuMjUzIiwibmFtZSI6IkZyYW5jZXNjbyBEaXN0ZWZhbm8iLCJub25jZSI6Im9hREd4Rlp4TDhHUHFiNXotUEI0US1YcTljczh4Nkx0N250UmszQVpyQ00iLCJvaWQiOiI5OWM1NDhjMy00ZDVhLTQ5OWItYTU3YS00NGZmOTk5ZGNhNmQiLCJyaCI6IjAuQUFBQUpjY1JrNkFTVmsyRVZ3Nm9lSU93b3RmQWpKcEZ0Y2RHdjQ2UTlvSTBueDA1QUZ3LiIsInN1YiI6IlFFWlpoM3VZaFBCLTdNcTRfQWpjNzN3N0NENHJXSDFOU3dlRldXS001TTQiLCJ0aWQiOiI5MzExYzcyNS0xMmEwLTRkNTYtODQ1Ny0wZWE4Nzg4M2IwYTIiLCJ1bmlxdWVfbmFtZSI6InRlc3QtdXNlckBzeW5hcHNlc2xhYi5vbm1pY3Jvc29mdC5jb20iLCJ1cG4iOiJ0ZXN0LXVzZXJAc3luYXBzZXNsYWIub25taWNyb3NvZnQuY29tIiwidXRpIjoiLXdVb0FHWjFLMGVvUlVlSnZ2ZHpBQSIsInZlciI6IjEuMCJ9.RH6BJQmQGUtLjjVR_aC0jJxi0z1f_BUPV-1QJQdnM_pGaBGJRPG8GkHc-Y6EFN04iI6y_gnZIi_y56hztSSeOsYDW_zMZaaDFgWNkKxXO_gFyYeHw6ZjcuYc0mzQaTFHPNzcHDireqJ8foOAwLk0QQvmJAUZWrDiZEewUjl6X7BdbeiK4iPUG4MyHYMgql_LHzHlrUzWultEEFSkwfLbpl1jQNnqvLcBZ0ZWBJx_fetyGh_w_2Y5j7MMO-rPkLTcmlYRvMD3ZLh-CKqAtJitrhW7PEqdoHDOqV7lVpV1DaJ_p86NNFm3ShuZtAffr7Bh4N9bxu-RoAxO6yT2ZZjRcA
```

But I need the access token not the idToken.

**Comment by chenrujun** [comment]
@fr4ncesco .
Thank you for your detailed description.
Now I can reproduce your problem.

Now I'm investigating the problem. 

(cc @yiliuTo, if you found something, please share it here.)

**Pull request closed without merging**
